name: Python Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pipenv'

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

      - name: Run tests
        run: pipenv run pytest
      
      - name: Archive HTML outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-output
          path: output/*.html